os: linux
dist: jammy

jobs:
  include:
    - name: "job one"
      vm: 
        create:
          name: 30june_200k24_02
      script: 
        - echo "condition with job tjjestestt"
        - echo $TRAVIS_COMMIT_MESSAGE
        - sleep 50
